.\" Copyright (C) 2020 VirtualSquare. Project Leader: Renzo Davoli
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License,
.\" as published by the Free Software Foundation, either version 2
.\" of the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston,
.\" MA 02110-1301 USA.
.\"
.\" generated with Ronn-NG/v0.10.0
.\" http://github.com/apjanke/ronn-ng/tree/0.10.0-SNAPSHOT
.TH "LIBVDEPLUG_VDESL" "1" "November 2020" "VirtualSquare"
.SH "NAME"
\fBlibvdeplug_vdesl\fR \- vdesl vdeplug module: ethernet over serial link
.SH "SYNOPSIS"
libvdeplug_vdesl\.so
.SH "DESCRIPTION"
This libvdeplug module creates point\-to\-point virtual ethernet networks over serial links\.
.P
This module of libvdeplug4 can be used in any program supporting vde like \fBvde_plug\fR, \fBvdens\fR, \fBkvm\fR, \fBqemu\fR, \fBuser\-mode\-linux\fR and \fBvirtualbox\fR\.
.P
The vde_plug_url syntax of this module is the following:
.P
\fBvdesl://\fR\fIdevice_path\fR [ \fB[\fR OPTION [ /OPTION]\|\.\|\.\|\.\fB]\fR ]
.SH "OPTIONS"
.TP
\fBspeed\fR=\fIbaudrate\fR
Set the baud rate of the serial link\. This plugin supports the following baud rates: 9600, 19200, 38400, 57600, 115200, 230400, 460800, 500000, 576000, 921600, 1000000, 1152000, 1500000, 2000000, 2500000, 3000000, 3500000, 4000000\. High baud rates may not be supported by the uart hardware or could provide an unreliable service due to communication errors\. In order to achieve high speeds the cables should be short and properly shielded from electro\-magnetic noise\.
.SH "EXAMPLES"
Scenario: two hosts connected by a serial line\. e\.g\.: RS\-232 serial ports connected by a null modem cable, USB\-ttl cables or USB\-FTDI boards or UART pins of System\-on\-Chip point\-to\-point connected so that the RXD on one end is connected to TXD on the other and viceversa\.
.P
In the following we use the device \fB/dev/ttyAMA0\fR, this may be changed to address the actual device (e\.g\. \fB/dev/ttyS0\fR, \fB/dev/ttyS1\fR, \fB/dev/ttyUSB0\fR, \fB/dev/ttyACM0\fR\|\.\|\.\|\.)\. No other processes should be using the serial port (e\.g\. no getty\-login process should be active on it)\.
.P
The following command (on both hosts) creates two vde namespaces connected by a virtual point\-to\-point ethernet network\.
.IP "" 4
.nf
vdens vdesl:///dev/ttyAMA0
.fi
.IP "" 0
.P
Run the following command on both hosts to create a virtual interface named \fBvdesl0\fR on each end\. The two interfaces are connected by a 4Mbaud link\.
.IP "" 4
.nf
sudo vde_plug \-d tap://vdesl0 vdesl:///dev/ttyAMA0[speed=4000000]
.fi
.IP "" 0
.SH "NOTICE"
Virtual Distributed Ethernet is not related in any way with www\.vde\.com ("Verband der Elektrotechnik, Elektronik und Informationstechnik" i\.e\. the German "Association for Electrical, Electronic & Information Technologies")\.
.SH "SEE ALSO"
\fBvde_plug\fR(1), \fBvdens\fR(1)
.SH "AUTHOR"
VirtualSquare\. Project leader: Renzo Davoli
